name: Run PHPStan

# Run PHPStan to annotate the code

on:
  push:
    branches:
      - master

jobs:
  phpstan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer, cs2pr
          extensions: zip

      - name: Run composer install
        continue-on-error: true
        run: composer install

      - name: Run PHPStan to add annotations to the code
        continue-on-error: true
        run: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit 1G --no-progress --error-format=checkstyle | cs2pr